# Generated by Django 5.0.6 on 2024-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/images')),
                ('roll', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('students', models.ManyToManyField(to='App02.student')),
            ],
        ),
    ]
