# Generated by Django 5.0.6 on 2024-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='App01.course'),
        ),
    ]
